
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BCOM BFUNL BFUNY BGRAM BLEX BPARSER BYACC ECOM EFUNL EFUNY EGRAM EOF IGN LIT PREC TOK TS comm funL funY gram ig instructions literals preceList tokenList tsListPly-Simple : EOFPly-Simple : BLEX Lex BYACC Yacc EOFPly-Simple : BYACC Yacc BLEX Lex EOFLex : Vars FunsLex : Vars : Vars VarVars : Var : LIT literalsVar : IGN igVar : TOK tokenListFuns : Funs Fun EFUNLFuns : Fun : BFUNL funLYacc : '
    
_lr_action_items = {'EOF':([0,6,8,9,10,14,15,18,19,20,21,23,],[2,-12,-14,-4,-6,-5,22,-8,-9,-10,25,-11,]),'BLEX':([0,4,7,],[3,-14,14,]),'BYACC':([0,3,5,6,9,10,18,19,20,23,],[4,-5,8,-12,-4,-6,-8,-9,-10,-11,]),'$end':([1,2,22,25,],[0,-1,-2,-3,]),'LIT':([3,6,10,14,18,19,20,],[-7,11,-6,-7,-8,-9,-10,]),'IGN':([3,6,10,14,18,19,20,],[-7,12,-6,-7,-8,-9,-10,]),'TOK':([3,6,10,14,18,19,20,],[-7,13,-6,-7,-8,-9,-10,]),'BFUNL':([3,6,9,10,14,18,19,20,23,],[-7,-12,17,-6,-7,-8,-9,-10,-11,]),'literals':([11,],[18,]),'ig':([12,],[19,]),'tokenList':([13,],[20,]),'EFUNL':([16,24,],[23,-13,]),'funL':([17,],[24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Ply-Simple':([0,],[1,]),'Lex':([3,14,],[5,21,]),'Vars':([3,14,],[6,6,]),'Yacc':([4,8,],[7,15,]),'Funs':([6,],[9,]),'Var':([6,],[10,]),'Fun':([9,],[16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Ply-Simple","S'",1,None,None,None),
  ('Ply-Simple -> EOF','Ply-Simple',1,'p_plySimple_EOF','plySimple_yacc.py',7),
  ('Ply-Simple -> BLEX Lex BYACC Yacc EOF','Ply-Simple',5,'p_plySimple_BLEX','plySimple_yacc.py',10),
  ('Ply-Simple -> BYACC Yacc BLEX Lex EOF','Ply-Simple',5,'p_plySimple_BYACC','plySimple_yacc.py',13),
  ('Lex -> Vars Funs','Lex',2,'p_Lex_notEmpty','plySimple_yacc.py',16),
  ('Lex -> <empty>','Lex',0,'p_Lex_Empty','plySimple_yacc.py',19),
  ('Vars -> Vars Var','Vars',2,'p_Vars_notEmpty','plySimple_yacc.py',22),
  ('Vars -> <empty>','Vars',0,'p_Vars_Empty','plySimple_yacc.py',25),
  ('Var -> LIT literals','Var',2,'p_Var_Literals','plySimple_yacc.py',28),
  ('Var -> IGN ig','Var',2,'p_Var_Ignore','plySimple_yacc.py',31),
  ('Var -> TOK tokenList','Var',2,'p_Var_ListTok','plySimple_yacc.py',34),
  ('Funs -> Funs Fun EFUNL','Funs',3,'p_Funs_notEmpty','plySimple_yacc.py',37),
  ('Funs -> <empty>','Funs',0,'p_Funs_Empty','plySimple_yacc.py',40),
  ('Fun -> BFUNL funL','Fun',2,'p_Fun','plySimple_yacc.py',43),
  ('Yacc -> <empty>','Yacc',0,'p_Yacc','plySimple_yacc.py',46),
]
