
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BCOM BFUNL BFUNY BGRAM BLEX BPARSER BYACC ECOM EFUNL EFUNY EGRAM EOF IGN LIT PREC TOK TS comm funL funY gram ig instructions literals preceList tokenList tsListLex : BLEX Vars FunsVars : Vars VarVars : Var : LIT literalsVar : IGN igVar : TOK tokenListFuns : Funs Fun EFUNLFuns : Fun : BFUNL funL'
    
_lr_action_items = {'BLEX':([0,],[2,]),'$end':([1,2,3,4,5,11,12,13,14,],[0,-3,-8,-1,-2,-4,-5,-6,-7,]),'LIT':([2,3,5,11,12,13,],[-3,6,-2,-4,-5,-6,]),'IGN':([2,3,5,11,12,13,],[-3,7,-2,-4,-5,-6,]),'TOK':([2,3,5,11,12,13,],[-3,8,-2,-4,-5,-6,]),'BFUNL':([2,3,4,5,11,12,13,14,],[-3,-8,10,-2,-4,-5,-6,-7,]),'literals':([6,],[11,]),'ig':([7,],[12,]),'tokenList':([8,],[13,]),'EFUNL':([9,15,],[14,-9,]),'funL':([10,],[15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Lex':([0,],[1,]),'Vars':([2,],[3,]),'Funs':([3,],[4,]),'Var':([3,],[5,]),'Fun':([4,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Lex","S'",1,None,None,None),
  ('Lex -> BLEX Vars Funs','Lex',3,'p_Lex','plySimple_yacc.py',22),
  ('Vars -> Vars Var','Vars',2,'p_Vars_notEmpty','plySimple_yacc.py',25),
  ('Vars -> <empty>','Vars',0,'p_Vars_Empty','plySimple_yacc.py',28),
  ('Var -> LIT literals','Var',2,'p_Var_Literals','plySimple_yacc.py',31),
  ('Var -> IGN ig','Var',2,'p_Var_Ignore','plySimple_yacc.py',34),
  ('Var -> TOK tokenList','Var',2,'p_Var_ListTok','plySimple_yacc.py',37),
  ('Funs -> Funs Fun EFUNL','Funs',3,'p_Funs_notEmpty','plySimple_yacc.py',40),
  ('Funs -> <empty>','Funs',0,'p_Funs_Empty','plySimple_yacc.py',43),
  ('Fun -> BFUNL funL','Fun',2,'p_Fun','plySimple_yacc.py',46),
]
