
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBER VARStat : VAR '=' ExpStat : ExpExp : Exp '+' ExpExp : Exp '-' ExpExp : Exp '*' ExpExp : Exp '/' ExpExp : '-' ExpExp : '(' Exp ')'Exp : NUMBERExp : VAR"
    
_lr_action_items = {'VAR':([0,4,5,7,8,9,10,11,],[2,13,13,13,13,13,13,13,]),'-':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[4,-10,9,4,4,-9,4,4,4,4,4,9,-10,9,9,9,9,9,9,-8,]),'(':([0,4,5,7,8,9,10,11,],[5,5,5,5,5,5,5,5,]),'NUMBER':([0,4,5,7,8,9,10,11,],[6,6,6,6,6,6,6,6,]),'$end':([1,2,3,6,12,13,15,16,17,18,19,20,],[0,-10,-2,-9,-7,-10,-1,-3,-4,-5,-6,-8,]),'=':([2,],[7,]),'+':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,8,-9,8,-10,8,8,8,8,8,8,-8,]),'*':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,10,-9,10,-10,10,10,10,10,10,10,-8,]),'/':([2,3,6,12,13,14,15,16,17,18,19,20,],[-10,11,-9,11,-10,11,11,11,11,11,11,-8,]),')':([6,12,13,14,16,17,18,19,20,],[-9,-7,-10,20,-3,-4,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Stat':([0,],[1,]),'Exp':([0,4,5,7,8,9,10,11,],[3,12,14,15,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Stat","S'",1,None,None,None),
  ('Stat -> VAR = Exp','Stat',3,'p_Stat_p1','example1_yacc.py',34),
  ('Stat -> Exp','Stat',1,'p_Stat_p2','example1_yacc.py',38),
  ('Exp -> Exp + Exp','Exp',3,'p_Exp_p3','example1_yacc.py',42),
  ('Exp -> Exp - Exp','Exp',3,'p_Exp_p4','example1_yacc.py',46),
  ('Exp -> Exp * Exp','Exp',3,'p_Exp_p5','example1_yacc.py',50),
  ('Exp -> Exp / Exp','Exp',3,'p_Exp_p6','example1_yacc.py',54),
  ('Exp -> - Exp','Exp',2,'p_Exp_p7','example1_yacc.py',58),
  ('Exp -> ( Exp )','Exp',3,'p_Exp_p8','example1_yacc.py',62),
  ('Exp -> NUMBER','Exp',1,'p_Exp_p9','example1_yacc.py',66),
  ('Exp -> VAR','Exp',1,'p_Exp_p10','example1_yacc.py',70),
]
